version: '3'

services:

  redis:
    image: redis

  springboot:
    image: sophianachiba/spring_crud_h2_redis_pubsub:latest
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/jhooq-springboot-container
    ports:
      - 8080:8080
    links:
      - redis
  angular:
    image: sophianachiba/angular_crud_demo:latest
    ports:
      - 8081:80